Determine DB command based on distribution
MariaDB stopped including the `mysql` symlinks in the official Docker
images, so now the commands using `mysql` or `mysqldump` are failing
with newer MariaDB versions.

This commit adds logic to determine the appropriate commands to use
based on the MYSQL_DISTRIBUTION (as that was already used previously
for the `warden db upgrade` subcommand).

However, it seems like the upgrade subcommand has never worked! The
MYSQL_ variables are exctracted from the DB containter environment
variables, but the MYSQL_DISTRIBUTION was never added as an environment
variable in the DB containers. Running the upgrade command results in
the following:

ERROR: The upgrade command only supports MySQL and MariaDB
installations.

This commit changes the DB services to include the MYSQL_DISTRIBUTION
in the environment variables, so it can be used in the warden commands
as intended(?).